[tool.poetry]
name = "mofsyncondition"
version = "0.1.0"
description = "Tool for extracting synthesis condition of MOFs"
authors = ["Dinga Wonanke"]
license = "MIT"
readme = "README.md"
[tool.poetry.dependencies]
<<<<<<< HEAD
python = ">=3.8,<3.10"
=======
python = ">=3.9,<3.10"
>>>>>>> 9253cec (fixed)
spacy = "3.6.1"
inscriptis = "2.3.2"
requests = "2.31.0"
beautifulsoup4 = "4.12.2"
chemdataextractor = "1.3.0"
scikit-learn = "1.3.0"
<<<<<<< HEAD
#openpyxl = "^3.1.2"
matplotlib = "3.7.2"
seaborn = "0.12.2"
=======
matplotlib = "3.7.2"
seaborn = "0.12.2"
selenium = "4.16.0"
pubchempy = "1.0.4"
pymupdf = "1.23.12"
pint = "0.23"
scyjava = "1.10.1"
sentence-transformers = "3.4.1"
>>>>>>> 9253cec (fixed)

[tool.poetry.scripts]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
